#!/bin/bash
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
#Script Name: ganglia-tomcat-memory-thread-count 
#Date: Sep 06th, 2017. 
#Modified: Apr 17, 2018.
#Versioning: 0.1 = added few variables hostip, user and password in script.
#Author: Krishna Bagal.
#Info: Tomcat thread and memroy information/Value send to ganglia server.
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
value='^[0-9]+([.][0-9]+)?$'
hostip=`ip route get 1 | awk '{print $NF;exit}'`
user="USERNAME"
password="PASSWORD"

T8080=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8080 -u $user -a $password -m thread -w 999 -c 1000 -U "/manager" -C \"http-bio-8080\" |awk {'print $3'}`
M8080=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8080 -u $user -a $password -m mem -w 90 -c 99 | cut -d= -f2 |cut -d% -f1`
if ! [[ $T8080 =~ $value ]] ; 
then
           /usr/bin/gmetric --name  Tomcat-Thread-8080 --value 0 --type int32 --unit Count
else
           /usr/bin/gmetric --name  Tomcat-Thread-8080 --value $T8080 --type int32 --unit Count
fi
if ! [[ $M8080 =~ $value ]] ; 
then
           /usr/bin/gmetric --name  Tomcat-Memory-8080 --value 0 --type int32 --unit %
else
         
           /usr/bin/gmetric --name  Tomcat-Memory-8080 --value $M8080 --type int32 --unit %
fi
T8081=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8081 -u $user -a $password -m thread -w 999 -c 1000 -U "/manager" -C \"http-bio-8081\" |awk {'print $3'}`
M8081=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8081 -u $user -a $password -m mem -w 90 -c 99 | cut -d= -f2 |cut -d% -f1`
if ! [[ $T8081 =~ $value ]] ; 
then
           /usr/bin/gmetric --name  Tomcat-Thread-8081 --value 0 --type int32 --unit Count
else
           /usr/bin/gmetric --name  Tomcat-Thread-8081 --value $T8081 --type int32 --unit Count
fi
if ! [[ $M8081 =~ $value ]] ; 
then
           /usr/bin/gmetric --name  Tomcat-Memory-8081 --value 0 --type int32 --unit %
else
         
           /usr/bin/gmetric --name  Tomcat-Memory-8081 --value $M8081 --type int32 --unit %
fi
T8082=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8082 -u $user -a $password -m thread -w 999 -c 1000 -U "/manager" -C \"http-bio-8082\" |awk {'print $3'}`
M8082=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8082 -u $user -a $password -m mem -w 90 -c 99 | cut -d= -f2 |cut -d% -f1`
if ! [[ $T8082 =~ $value ]] ;
then
           /usr/bin/gmetric --name  Tomcat-Thread-8082 --value 0 --type int32 --unit Count
else
           /usr/bin/gmetric --name  Tomcat-Thread-8082 --value $T8082 --type int32 --unit Count
fi
if ! [[ $M8082 =~ $value ]] ;
then
           /usr/bin/gmetric --name  Tomcat-Memory-8082 --value 0 --type int32 --unit %
else
           /usr/bin/gmetric --name  Tomcat-Memory-8082 --value $M8082 --type int32 --unit %
fi
T8083=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8083 -u $user -a $password -m thread -w 999 -c 1000 -U "/manager" -C \"http-bio-8083\" |awk {'print $3'}`
M8083=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8083 -u $user -a $password -m mem -w 90 -c 99 | cut -d= -f2 |cut -d% -f1`
if ! [[ $T8083 =~ $value ]] ;
then
           /usr/bin/gmetric --name  Tomcat-Thread-8083 --value 0 --type int32 --unit Count
else
           /usr/bin/gmetric --name  Tomcat-Thread-8083 --value $T8083 --type int32 --unit Count
fi
if ! [[ $M8083 =~ $value ]] ;
then
           /usr/bin/gmetric --name  Tomcat-Memory-8083 --value 0 --type int32 --unit %
else
           /usr/bin/gmetric --name  Tomcat-Memory-8083 --value $M8083 --type int32 --unit %
fi
T8084=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8084 -u $user -a $password -m thread -w 999 -c 1000 -U "/manager" -C \"http-bio-8084\" |awk {'print $3'}`
M8084=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8084 -u $user -a $password -m mem -w 90 -c 99 | cut -d= -f2 |cut -d% -f1`
if ! [[ $T8084 =~ $value ]] ;
then
           /usr/bin/gmetric --name  Tomcat-Thread-8084 --value 0 --type int32 --unit Count
else
           /usr/bin/gmetric --name  Tomcat-Thread-8084 --value $T8084 --type int32 --unit Count
fi
if ! [[ $M8084 =~ $value ]] ;
then
           /usr/bin/gmetric --name  Tomcat-Memory-8084 --value 0 --type int32 --unit %
else
           /usr/bin/gmetric --name  Tomcat-Memory-8084 --value $M8084 --type int32 --unit %
fi
T8085=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8085 -u $user -a $password -m thread -w 999 -c 1000 -U "/manager" -C \"http-bio-8085\" |awk {'print $3'}`
M8085=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8085 -u $user -a $password -m mem -w 90 -c 99 | cut -d= -f2 |cut -d% -f1`
if ! [[ $T8085 =~ $value ]] ;
then
           /usr/bin/gmetric --name  Tomcat-Thread-8085 --value 0 --type int32 --unit Count
else
           /usr/bin/gmetric --name  Tomcat-Thread-8085 --value $T8085 --type int32 --unit Count
fi
if ! [[ $M8085 =~ $value ]] ;
then
           /usr/bin/gmetric --name  Tomcat-Memory-8085 --value 0 --type int32 --unit %
else
           /usr/bin/gmetric --name  Tomcat-Memory-8085 --value $M8085 --type int32 --unit %
fi
T8086=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8086 -u $user -a $password -m thread -w 999 -c 1000 -U "/manager" -C \"http-bio-8086\" |awk {'print $3'}`
M8086=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8086 -u $user -a $password -m mem -w 90 -c 99 | cut -d= -f2 |cut -d% -f1`
if ! [[ $T8086 =~ $value ]] ;
then
           /usr/bin/gmetric --name  Tomcat-Thread-8086 --value 0 --type int32 --unit Count
else
           /usr/bin/gmetric --name  Tomcat-Thread-8086 --value $T8086 --type int32 --unit Count
fi
if ! [[ $M8086 =~ $value ]] ;
then
           /usr/bin/gmetric --name  Tomcat-Memory-8086 --value 0 --type int32 --unit %
else
           /usr/bin/gmetric --name  Tomcat-Memory-8086 --value $M8086 --type int32 --unit %
fi
T8087=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8087 -u $user -a $password -m thread -w 999 -c 1000 -U "/manager" -C \"http-bio-8087\" |awk {'print $3'}`
M8087=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8087 -u $user -a $password -m mem -w 90 -c 99 | cut -d= -f2 |cut -d% -f1`
if ! [[ $T8087 =~ $value ]] ;
then
           /usr/bin/gmetric --name  Tomcat-Thread-8087 --value 0 --type int32 --unit Count
else
           /usr/bin/gmetric --name  Tomcat-Thread-8087 --value $T8087 --type int32 --unit Count
fi
if ! [[ $M8087 =~ $value ]] ;
then
           /usr/bin/gmetric --name  Tomcat-Memory-8087 --value 0 --type int32 --unit %
else
           /usr/bin/gmetric --name  Tomcat-Memory-8087 --value $M8087 --type int32 --unit %
fi
T8088=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8088 -u $user -a $password -m thread -w 999 -c 1000 -U "/manager" -C \"http-bio-8088\" |awk {'print $3'}`
M8088=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8088 -u $user -a $password -m mem -w 90 -c 99 | cut -d= -f2 |cut -d% -f1`
if ! [[ $T8088 =~ $value ]] ;
then
           /usr/bin/gmetric --name  Tomcat-Thread-8088 --value 0 --type int32 --unit Count
else
           /usr/bin/gmetric --name  Tomcat-Thread-8088 --value $T8088 --type int32 --unit Count
fi
if ! [[ $M8088 =~ $value ]] ;
then
           /usr/bin/gmetric --name  Tomcat-Memory-8088 --value 0 --type int32 --unit %
else
           /usr/bin/gmetric --name  Tomcat-Memory-8088 --value $M8088 --type int32 --unit %
fi
T8089=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8089 -u $user -a $password -m thread -w 999 -c 1000 -U "/manager" -C \"http-bio-8089\" |awk {'print $3'}`
M8089=`/usr/local/bin/scripts/check_tomcat.py -H $hostip -p 8089 -u $user -a $password -m mem -w 90 -c 99 | cut -d= -f2 |cut -d% -f1`
if ! [[ $T8089 =~ $value ]] ;
then
           /usr/bin/gmetric --name  Tomcat-Thread-8089 --value 0 --type int32 --unit Count
else
           /usr/bin/gmetric --name  Tomcat-Thread-8089 --value $T8089 --type int32 --unit Count
fi
if ! [[ $M8089 =~ $value ]] ;
then
           /usr/bin/gmetric --name  Tomcat-Memory-8089 --value 0 --type int32 --unit %
else
           /usr/bin/gmetric --name  Tomcat-Memory-8089 --value $M8089 --type int32 --unit %
fi
